version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    security-updates-only: true

  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
